name: "Active Languages"

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/active-languages
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Remove packageManager
        run: jq 'del(.packageManager)' package.json > package.tmp && mv package.tmp package.json

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        id: pnpm-install
        with:
          version: 10
          run_install: true

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install APT dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake pkg-config libicu-dev zlib1g-dev libcurl4-openssl-dev libssl-dev ruby-dev

      - name: Install GitHub Linguist
        if: steps.cache-linguist.outputs.cache-hit != 'true'
        run: sudo gem install github-linguist

      - run: pnpm al:build
      - run: pnpm al:start
        env:
          GH_USERNAME: ${{ github.actor }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

          AL_GIST_ID: ${{ vars.AL_GIST_ID }}

          EXCLUDE_LANG: ${{ vars.EXCLUDE_LANG }}
