name: Total Languages

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  language-box:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Remove packageManager
        run: jq 'del(.packageManager)' package.json > package.tmp && mv package.tmp package.json

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        id: pnpm-install
        with:
          version: 10
          run_install: true

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - run: pnpm tl:build
      - run: pnpm tl:start
        env:
          GH_USERNAME: ${{ github.actor }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

          TL_GIST_ID: ${{ vars.TL_GIST_ID }}
          TL_GIST_DESCRIPTION: ${{ vars.TL_GIST_DESCRIPTION }}

          EXCLUDE_LANG: ${{ vars.EXCLUDE_LANG }}
          EXCLUDE_REPO: ${{ vars.EXCLUDE_REPO }}
